# Generated by Django 5.2.5 on 2025-08-11 14:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('nss', models.CharField(blank=True, max_length=15)),
                ('fecha_ingreso', models.DateField()),
                ('paquete_documentos', models.FileField(blank=True, upload_to='expedientes/')),
                ('notas', models.TextField(blank=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='app.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetodologiaDigitalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.CharField(choices=[('Contrato', 'Contrato'), ('Expediente', 'Expediente'), ('Otro', 'Otro')], max_length=30)),
                ('resolucion_dpi', models.PositiveIntegerField(default=300)),
                ('fecha_meta', models.DateField()),
                ('lineamientos', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Capacitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tema', models.CharField(max_length=200)),
                ('programa', models.CharField(blank=True, max_length=200)),
                ('modalidad', models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixta', 'Mixta')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('participantes_estimados', models.PositiveIntegerField(default=1)),
                ('evidencia', models.FileField(blank=True, upload_to='capacitaciones/')),
                ('notas', models.TextField(blank=True)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacitaciones_responsable', to='app.empleado')),
                ('normas', models.ManyToManyField(blank=True, related_name='capacitaciones', to='app.norma')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomologacionSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documento_equivalente', models.CharField(max_length=200)),
                ('propuesta', models.TextField()),
                ('adjunto', models.FileField(blank=True, upload_to='homologacion/')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.empleado')),
                ('normas_involucradas', models.ManyToManyField(related_name='homologaciones', to='app.norma')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proceso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proceso_texto', models.CharField(blank=True, help_text='Nombre del proceso si no existe en catálogo', max_length=200)),
                ('equipo', models.TextField(blank=True, help_text='Nombres separados por coma')),
                ('es_proveedor', models.BooleanField(default=False)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('anexos', models.FileField(blank=True, upload_to='auditorias/')),
                ('alcance', models.TextField(blank=True)),
                ('auditor_lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_lider', to='app.empleado')),
                ('normas_a_auditar', models.ManyToManyField(related_name='auditorias', to='app.norma')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.proceso')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoSGC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Procedimiento', 'Procedimiento'), ('Instructivo', 'Instructivo'), ('Formato', 'Formato'), ('Política', 'Política')], max_length=30)),
                ('codigo', models.CharField(max_length=50)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('En revisión', 'En revisión'), ('Aprobado', 'Aprobado'), ('Obsoleto', 'Obsoleto')], default='Borrador', max_length=20)),
                ('archivo', models.FileField(blank=True, upload_to='documentos/')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True)),
                ('propietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_propietario', to='app.empleado')),
                ('revisores', models.ManyToManyField(blank=True, related_name='documentos_a_revisar', to='app.empleado')),
            ],
            options={
                'unique_together': {('codigo', 'version')},
            },
        ),
    ]
